name: Deploy to WordPress.org
on:
  push:
    tags:
      - "v*"
  pull_request:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Copy files to dist
        run: |
          mkdir -p dist
          rsync -av --progress ./ dist/ \
          -x '/.idea/*' \
          -x '.DS_Store' \
          -x '*.dist' \
          -x '/vendor/*' \
          -x '*/node_modules/*' \
          -x '.git*' \
          -x 'composer.*' \
          -x 'package*.json' \
          -x '*.zip'

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: dist/
          SLUG: search-tracker