name: Deploy to WordPress.org
on:
  push:
    tags:
      - "v*"
  pull_request:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Copy files to dist
        run: |
          mkdir -p dist
          rsync -av --progress ./ dist/ \
          --exclude='.idea' \
          --exclude='.DS_Store' \
          --exclude='*.dist' \
          --exclude='vendor' \
          --exclude='node_modules' \
          --exclude='.git' \
          --exclude='.gitignore' \
          --exclude='composer.*' \
          --exclude='package*.json' \
          --exclude='*.zip' \
          --exclude='dist'

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: dist/
          SLUG: search-tracker